// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq-generated-code.md

import type { WideOperationArgument } from '../../../../../../types.ts';
import type { OmitValueWhenNever } from '../../../../../../types.ts';
import type { COUNTERFACT_RESPONSE } from '../../../../../../types.ts';
import type { Context } from '../../../../../../routes/_.context.ts';

export type HTTP_GET = {
  /* error creating export "HTTP_GET" for types/paths/notifications/v1/subscriptions/{notificationType}/{subscriptionId}.types.ts: TypeError: Cannot read properties of undefined (reading 'data')
    at file:///Users/sergei/.npm/_npx/e8d1761dc3fb6aab/node_modules/counterfact/dist/typescript-generator/operation-type-coder.js:79:88
    at file:///Users/sergei/.npm/_npx/e8d1761dc3fb6aab/node_modules/counterfact/dist/typescript-generator/requirement.js:49:41
    at file:///Users/sergei/.npm/_npx/e8d1761dc3fb6aab/node_modules/counterfact/dist/typescript-generator/requirement.js:35:13
    at Array.forEach (<anonymous>)
    at Requirement.forEach (file:///Users/sergei/.npm/_npx/e8d1761dc3fb6aab/node_modules/counterfact/dist/typescript-generator/requirement.js:34:32)
    at Requirement.find (file:///Users/sergei/.npm/_npx/e8d1761dc3fb6aab/node_modules/counterfact/dist/typescript-generator/requirement.js:48:14)
    at OperationTypeCoder.writeCode (file:///Users/sergei/.npm/_npx/e8d1761dc3fb6aab/node_modules/counterfact/dist/typescript-generator/operation-type-coder.js:79:19)
    at OperationTypeCoder.write (file:///Users/sergei/.npm/_npx/e8d1761dc3fb6aab/node_modules/counterfact/dist/typescript-generator/type-coder.js:7:21)
    at file:///Users/sergei/.npm/_npx/e8d1761dc3fb6aab/node_modules/counterfact/dist/typescript-generator/script.js:50:51
    at async Promise.all (index 0) */
};

export type HTTP_DELETE = {
  /* error creating export "HTTP_DELETE" for types/paths/notifications/v1/subscriptions/{notificationType}/{subscriptionId}.types.ts: TypeError: Cannot read properties of undefined (reading 'data')
    at file:///Users/sergei/.npm/_npx/e8d1761dc3fb6aab/node_modules/counterfact/dist/typescript-generator/operation-type-coder.js:79:88
    at file:///Users/sergei/.npm/_npx/e8d1761dc3fb6aab/node_modules/counterfact/dist/typescript-generator/requirement.js:49:41
    at file:///Users/sergei/.npm/_npx/e8d1761dc3fb6aab/node_modules/counterfact/dist/typescript-generator/requirement.js:35:13
    at Array.forEach (<anonymous>)
    at Requirement.forEach (file:///Users/sergei/.npm/_npx/e8d1761dc3fb6aab/node_modules/counterfact/dist/typescript-generator/requirement.js:34:32)
    at Requirement.find (file:///Users/sergei/.npm/_npx/e8d1761dc3fb6aab/node_modules/counterfact/dist/typescript-generator/requirement.js:48:14)
    at OperationTypeCoder.writeCode (file:///Users/sergei/.npm/_npx/e8d1761dc3fb6aab/node_modules/counterfact/dist/typescript-generator/operation-type-coder.js:79:19)
    at OperationTypeCoder.write (file:///Users/sergei/.npm/_npx/e8d1761dc3fb6aab/node_modules/counterfact/dist/typescript-generator/type-coder.js:7:21)
    at file:///Users/sergei/.npm/_npx/e8d1761dc3fb6aab/node_modules/counterfact/dist/typescript-generator/script.js:50:51
    at async Promise.all (index 1) */
};
