// Generated by ts-to-zod
import { z } from 'zod';

export const getOrdersQuerySchema = z.object({
  CreatedAfter: z.string().optional(),
  CreatedBefore: z.string().optional(),
  LastUpdatedAfter: z.string().optional(),
  LastUpdatedBefore: z.string().optional(),
  OrderStatuses: z.union([z.array(z.string()), z.string()]).optional(),
  MarketplaceIds: z.union([z.array(z.string()), z.string()]),
  FulfillmentChannels: z.union([z.array(z.string()), z.string()]).optional(),
  PaymentMethods: z.union([z.array(z.string()), z.string()]).optional(),
  BuyerEmail: z.string().optional(),
  SellerOrderId: z.string().optional(),
  MaxResultsPerPage: z.number().optional(),
  EasyShipShipmentStatuses: z
    .union([z.array(z.string()), z.string()])
    .optional(),
  ElectronicInvoiceStatuses: z
    .union([z.array(z.string()), z.string()])
    .optional(),
  NextToken: z.string().optional(),
  AmazonOrderIds: z.union([z.array(z.string()), z.string()]).optional(),
  ActualFulfillmentSupplySourceId: z.string().optional(),
  IsISPU: z.boolean().optional(),
  StoreChainStoreId: z.string().optional(),
  EarliestDeliveryDateBefore: z.string().optional(),
  EarliestDeliveryDateAfter: z.string().optional(),
  LatestDeliveryDateBefore: z.string().optional(),
  LatestDeliveryDateAfter: z.string().optional(),
});

export const getOrderItemsQuerySchema = z.object({
  NextToken: z.string().optional(),
});

export const getOrderItemsBuyerInfoQuerySchema = z.object({
  NextToken: z.string().optional(),
});

export const getSubscriptionQuerySchema = z.object({
  payloadVersion: z.string().optional(),
});
