// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq-generated-code.md

import type { WideOperationArgument } from "../../../../types.ts";
import type { OmitValueWhenNever } from "../../../../types.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../types.ts";
import type { Context } from "../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../types.ts";
import type { CreateRestrictedDataTokenRequest } from "../../../definitions/CreateRestrictedDataTokenRequest.js";
import type { CreateRestrictedDataTokenResponse } from "../../../definitions/CreateRestrictedDataTokenResponse.js";
import type { ErrorList } from "../../../definitions/ErrorList.js";

export type HTTP_POST = (
  $: OmitValueWhenNever<{
    query: never;
    path: never;
    header: never;
    body: CreateRestrictedDataTokenRequest;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: {
          "x-amzn-RateLimit-Limit": { schema: string };
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: CreateRestrictedDataTokenResponse;
          };
        };
      };
      400: {
        headers: {
          "x-amzn-RateLimit-Limit": { schema: string };
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ErrorList;
          };
        };
      };
      401: {
        headers: {
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ErrorList;
          };
        };
      };
      403: {
        headers: {
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ErrorList;
          };
        };
      };
      404: {
        headers: {
          "x-amzn-RateLimit-Limit": { schema: string };
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ErrorList;
          };
        };
      };
      415: {
        headers: {
          "x-amzn-RateLimit-Limit": { schema: string };
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ErrorList;
          };
        };
      };
      429: {
        headers: {
          "x-amzn-RateLimit-Limit": { schema: string };
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ErrorList;
          };
        };
      };
      500: {
        headers: {
          "x-amzn-RateLimit-Limit": { schema: string };
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ErrorList;
          };
        };
      };
      503: {
        headers: {
          "x-amzn-RateLimit-Limit": { schema: string };
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: ErrorList;
          };
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
  }>,
) =>
  | {
      status: 200;
      contentType?: "application/json";
      body?: CreateRestrictedDataTokenResponse;
    }
  | {
      status: 400;
      contentType?: "application/json";
      body?: ErrorList;
    }
  | {
      status: 401;
      contentType?: "application/json";
      body?: ErrorList;
    }
  | {
      status: 403;
      contentType?: "application/json";
      body?: ErrorList;
    }
  | {
      status: 404;
      contentType?: "application/json";
      body?: ErrorList;
    }
  | {
      status: 415;
      contentType?: "application/json";
      body?: ErrorList;
    }
  | {
      status: 429;
      contentType?: "application/json";
      body?: ErrorList;
    }
  | {
      status: 500;
      contentType?: "application/json";
      body?: ErrorList;
    }
  | {
      status: 503;
      contentType?: "application/json";
      body?: ErrorList;
    }
  | { status: 415; contentType: "text/plain"; body: string }
  | COUNTERFACT_RESPONSE
  | { ALL_REMAINING_HEADERS_ARE_OPTIONAL: COUNTERFACT_RESPONSE };
