// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq-generated-code.md

import type { WideOperationArgument } from '../../../../../../../types.ts';
import type { OmitValueWhenNever } from '../../../../../../../types.ts';
import type { COUNTERFACT_RESPONSE } from '../../../../../../../types.ts';
import type { Context } from '../../../../../../../routes/_.context.ts';
import type { ResponseBuilderFactory } from '../../../../../../../types.ts';
import type { GetOrderItemsBuyerInfoResponse } from '../../../../../../definitions/GetOrderItemsBuyerInfoResponse.js';

export type HTTP_GET = (
  $: OmitValueWhenNever<{
    query: { NextToken?: string };
    path: { orderId: string };
    header: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: {
          'x-amzn-RateLimit-Limit': { schema: string };
          'x-amzn-RequestId': { schema: string };
        };
        requiredHeaders: never;
        content: {
          'application/json': {
            schema: GetOrderItemsBuyerInfoResponse;
          };
        };
      };
      400: {
        headers: {
          'x-amzn-RateLimit-Limit': { schema: string };
          'x-amzn-RequestId': { schema: string };
        };
        requiredHeaders: never;
        content: {
          'application/json': {
            schema: GetOrderItemsBuyerInfoResponse;
          };
        };
      };
      403: {
        headers: {
          'x-amzn-RequestId': { schema: string };
        };
        requiredHeaders: never;
        content: {
          'application/json': {
            schema: GetOrderItemsBuyerInfoResponse;
          };
        };
      };
      404: {
        headers: {
          'x-amzn-RateLimit-Limit': { schema: string };
          'x-amzn-RequestId': { schema: string };
        };
        requiredHeaders: never;
        content: {
          'application/json': {
            schema: GetOrderItemsBuyerInfoResponse;
          };
        };
      };
      429: {
        headers: {
          'x-amzn-RequestId': { schema: string };
        };
        requiredHeaders: never;
        content: {
          'application/json': {
            schema: GetOrderItemsBuyerInfoResponse;
          };
        };
      };
      500: {
        headers: {
          'x-amzn-RequestId': { schema: string };
        };
        requiredHeaders: never;
        content: {
          'application/json': {
            schema: GetOrderItemsBuyerInfoResponse;
          };
        };
      };
      503: {
        headers: {
          'x-amzn-RequestId': { schema: string };
        };
        requiredHeaders: never;
        content: {
          'application/json': {
            schema: GetOrderItemsBuyerInfoResponse;
          };
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
  }>
) =>
  | {
      status: 200;
      contentType?: 'application/json';
      body?: GetOrderItemsBuyerInfoResponse;
    }
  | {
      status: 400;
      contentType?: 'application/json';
      body?: GetOrderItemsBuyerInfoResponse;
    }
  | {
      status: 403;
      contentType?: 'application/json';
      body?: GetOrderItemsBuyerInfoResponse;
    }
  | {
      status: 404;
      contentType?: 'application/json';
      body?: GetOrderItemsBuyerInfoResponse;
    }
  | {
      status: 429;
      contentType?: 'application/json';
      body?: GetOrderItemsBuyerInfoResponse;
    }
  | {
      status: 500;
      contentType?: 'application/json';
      body?: GetOrderItemsBuyerInfoResponse;
    }
  | {
      status: 503;
      contentType?: 'application/json';
      body?: GetOrderItemsBuyerInfoResponse;
    }
  | { status: 415; contentType: 'text/plain'; body: string }
  | COUNTERFACT_RESPONSE
  | { ALL_REMAINING_HEADERS_ARE_OPTIONAL: COUNTERFACT_RESPONSE };
