// This code was automatically generated from an OpenAPI description.
// Do not edit this file. Edit the OpenAPI file instead.
// For more information, see https://github.com/pmcelhaney/counterfact/blob/main/docs/faq-generated-code.md

import type { WideOperationArgument } from "../../../../../../types.ts";
import type { OmitValueWhenNever } from "../../../../../../types.ts";
import type { COUNTERFACT_RESPONSE } from "../../../../../../types.ts";
import type { Context } from "../../../../../../routes/_.context.ts";
import type { ResponseBuilderFactory } from "../../../../../../types.ts";
import type { GetOrderRegulatedInfoResponse } from "../../../../../definitions/GetOrderRegulatedInfoResponse.js";
import type { UpdateVerificationStatusRequest } from "../../../../../definitions/UpdateVerificationStatusRequest.js";
import type { UpdateVerificationStatusErrorResponse } from "../../../../../definitions/UpdateVerificationStatusErrorResponse.js";

export type HTTP_GET = (
  $: OmitValueWhenNever<{
    query: never;
    path: { orderId: string };
    header: never;
    body: never;
    context: Context;
    response: ResponseBuilderFactory<{
      200: {
        headers: {
          "x-amzn-RateLimit-Limit": { schema: string };
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: GetOrderRegulatedInfoResponse;
          };
        };
      };
      400: {
        headers: {
          "x-amzn-RateLimit-Limit": { schema: string };
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: GetOrderRegulatedInfoResponse;
          };
        };
      };
      403: {
        headers: {
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: GetOrderRegulatedInfoResponse;
          };
        };
      };
      404: {
        headers: {
          "x-amzn-RateLimit-Limit": { schema: string };
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: GetOrderRegulatedInfoResponse;
          };
        };
      };
      429: {
        headers: {
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: GetOrderRegulatedInfoResponse;
          };
        };
      };
      500: {
        headers: {
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: GetOrderRegulatedInfoResponse;
          };
        };
      };
      503: {
        headers: {
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: GetOrderRegulatedInfoResponse;
          };
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
  }>,
) =>
  | {
      status: 200;
      contentType?: "application/json";
      body?: GetOrderRegulatedInfoResponse;
    }
  | {
      status: 400;
      contentType?: "application/json";
      body?: GetOrderRegulatedInfoResponse;
    }
  | {
      status: 403;
      contentType?: "application/json";
      body?: GetOrderRegulatedInfoResponse;
    }
  | {
      status: 404;
      contentType?: "application/json";
      body?: GetOrderRegulatedInfoResponse;
    }
  | {
      status: 429;
      contentType?: "application/json";
      body?: GetOrderRegulatedInfoResponse;
    }
  | {
      status: 500;
      contentType?: "application/json";
      body?: GetOrderRegulatedInfoResponse;
    }
  | {
      status: 503;
      contentType?: "application/json";
      body?: GetOrderRegulatedInfoResponse;
    }
  | { status: 415; contentType: "text/plain"; body: string }
  | COUNTERFACT_RESPONSE
  | { ALL_REMAINING_HEADERS_ARE_OPTIONAL: COUNTERFACT_RESPONSE };

export type HTTP_PATCH = (
  $: OmitValueWhenNever<{
    query: never;
    path: { orderId: string };
    header: never;
    body: UpdateVerificationStatusRequest;
    context: Context;
    response: ResponseBuilderFactory<{
      204: {
        headers: {
          "x-amzn-RateLimit-Limit": { schema: string };
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: never;
      };
      400: {
        headers: {
          "x-amzn-RateLimit-Limit": { schema: string };
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UpdateVerificationStatusErrorResponse;
          };
        };
      };
      403: {
        headers: {
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UpdateVerificationStatusErrorResponse;
          };
        };
      };
      404: {
        headers: {
          "x-amzn-RateLimit-Limit": { schema: string };
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UpdateVerificationStatusErrorResponse;
          };
        };
      };
      413: {
        headers: {
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UpdateVerificationStatusErrorResponse;
          };
        };
      };
      415: {
        headers: {
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UpdateVerificationStatusErrorResponse;
          };
        };
      };
      429: {
        headers: {
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UpdateVerificationStatusErrorResponse;
          };
        };
      };
      500: {
        headers: {
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UpdateVerificationStatusErrorResponse;
          };
        };
      };
      503: {
        headers: {
          "x-amzn-RequestId": { schema: string };
        };
        requiredHeaders: never;
        content: {
          "application/json": {
            schema: UpdateVerificationStatusErrorResponse;
          };
        };
      };
    }>;
    x: WideOperationArgument;
    proxy: (url: string) => COUNTERFACT_RESPONSE;
    user: never;
  }>,
) =>
  | {
      status: 204;
    }
  | {
      status: 400;
      contentType?: "application/json";
      body?: UpdateVerificationStatusErrorResponse;
    }
  | {
      status: 403;
      contentType?: "application/json";
      body?: UpdateVerificationStatusErrorResponse;
    }
  | {
      status: 404;
      contentType?: "application/json";
      body?: UpdateVerificationStatusErrorResponse;
    }
  | {
      status: 413;
      contentType?: "application/json";
      body?: UpdateVerificationStatusErrorResponse;
    }
  | {
      status: 415;
      contentType?: "application/json";
      body?: UpdateVerificationStatusErrorResponse;
    }
  | {
      status: 429;
      contentType?: "application/json";
      body?: UpdateVerificationStatusErrorResponse;
    }
  | {
      status: 500;
      contentType?: "application/json";
      body?: UpdateVerificationStatusErrorResponse;
    }
  | {
      status: 503;
      contentType?: "application/json";
      body?: UpdateVerificationStatusErrorResponse;
    }
  | { status: 415; contentType: "text/plain"; body: string }
  | COUNTERFACT_RESPONSE
  | { ALL_REMAINING_HEADERS_ARE_OPTIONAL: COUNTERFACT_RESPONSE };
