import type { AssociatedItem } from "./AssociatedItem.js";
import type { ProductInfoDetail } from "./ProductInfoDetail.js";
import type { PointsGrantedDetail } from "./PointsGrantedDetail.js";
import type { Money } from "./Money.js";
import type { PromotionIdList } from "./PromotionIdList.js";
import type { TaxCollection } from "./TaxCollection.js";
import type { ItemBuyerInfo } from "./ItemBuyerInfo.js";
import type { BuyerRequestedCancel } from "./BuyerRequestedCancel.js";
import type { SubstitutionPreferences } from "./SubstitutionPreferences.js";
import type { Measurement } from "./Measurement.js";
import type { ShippingConstraints } from "./ShippingConstraints.js";
import type { AmazonPrograms } from "./AmazonPrograms.js";

export type OrderItem = {
  ASIN: string;
  SellerSKU?: string;
  OrderItemId: string;
  AssociatedItems?: Array<AssociatedItem>;
  Title?: string;
  QuantityOrdered: number;
  QuantityShipped?: number;
  ProductInfo?: ProductInfoDetail;
  PointsGranted?: PointsGrantedDetail;
  ItemPrice?: Money;
  ShippingPrice?: Money;
  ItemTax?: Money;
  ShippingTax?: Money;
  ShippingDiscount?: Money;
  ShippingDiscountTax?: Money;
  PromotionDiscount?: Money;
  PromotionDiscountTax?: Money;
  PromotionIds?: PromotionIdList;
  CODFee?: Money;
  CODFeeDiscount?: Money;
  IsGift?: string;
  ConditionNote?: string;
  ConditionId?: string;
  ConditionSubtypeId?: string;
  ScheduledDeliveryStartDate?: string;
  ScheduledDeliveryEndDate?: string;
  PriceDesignation?: string;
  TaxCollection?: TaxCollection;
  SerialNumberRequired?: boolean;
  IsTransparency?: boolean;
  IossNumber?: string;
  StoreChainStoreId?: string;
  DeemedResellerCategory?: "IOSS" | "UOSS";
  BuyerInfo?: ItemBuyerInfo;
  BuyerRequestedCancel?: BuyerRequestedCancel;
  SerialNumbers?: Array<string>;
  SubstitutionPreferences?: SubstitutionPreferences;
  Measurement?: Measurement;
  ShippingConstraints?: ShippingConstraints;
  AmazonPrograms?: AmazonPrograms;
};
